# Generated by Django 3.2.13 on 2022-05-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=100, unique=True)),
                ('diagnosis', models.CharField(max_length=256, null=True, default=None)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('age_category', models.IntegerField(null=True)),
                ('dosimetry', models.CharField(max_length=100, null=True)),
                ('exposed_region', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('site', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('subtype', models.CharField(max_length=100, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tumor_size', models.CharField(max_length=100, null=True)),
                ('t_status', models.CharField(max_length=16, null=True)),
                ('n_status', models.CharField(max_length=16, null=True)),
                ('m_status', models.CharField(max_length=16, null=True)),
                ('clinical_stage', models.CharField(max_length=32, null=True)),
                ('operation_type', models.CharField(max_length=100, null=True)),
                ('relapse', models.BooleanField(default=False)),
                ('radio_treatment', models.BooleanField(default=False)),
                ('tsh_suppression', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor')),
            ],
        ),
    ]
