# Generated by Django 3.2.13 on 2022-12-19 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical_Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=-1)),
                ('patient_uid', models.CharField(max_length=45, null=True)),
                ('edition', models.CharField(default=None, max_length=10, null=True)),
                ('classification_tumour', models.CharField(default=None, max_length=10, null=True)),
                ('classification_normal', models.CharField(default=None, max_length=10, null=True)),
                ('classification_metastatic', models.CharField(default=None, max_length=10, null=True)),
                ('stage', models.CharField(default=None, max_length=45, null=True)),
                ('operation_type', models.CharField(default=None, max_length=45, null=True)),
                ('relapse', models.BooleanField(default=False)),
                ('rit', models.BooleanField(default=False)),
                ('rit_value', models.IntegerField(default=None, null=True)),
                ('tsh_suppression', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=None, null=True)),
                ('patient_uid', models.CharField(default=None, max_length=20, null=True)),
                ('gender', models.CharField(default=None, max_length=10, null=True)),
                ('oblast_at_accident', models.CharField(default=None, max_length=45, null=True)),
                ('country_at_accident', models.CharField(default=None, max_length=45, null=True)),
                ('diagnosis', models.CharField(default=None, max_length=15, null=True)),
                ('age_at_first_operation', models.IntegerField(default=None, null=True)),
                ('age_at_exposure', models.IntegerField(default=None, null=True)),
                ('age_category', models.IntegerField(default=None, null=True)),
                ('dosimetry', models.DecimalField(decimal_places=10, default=None, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uid', models.CharField(max_length=10, null=True)),
                ('gene', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('patient_uid', models.CharField(max_length=20)),
                ('item_uid', models.CharField(default=None, max_length=45, null=True)),
                ('type', models.CharField(max_length=20)),
                ('subtype', models.CharField(default=None, max_length=20, null=True)),
                ('origin', models.CharField(default=None, max_length=20, null=True)),
                ('tnm_type', models.CharField(default=None, max_length=15, null=True)),
                ('diagnosis', models.CharField(max_length=45)),
                ('quantity', models.CharField(default=None, max_length=20, null=True)),
                ('quality', models.CharField(default=None, max_length=20, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('_STATUS', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled', max_length=256)),
                ('search_type', models.CharField(max_length=10)),
                ('case_count', models.IntegerField(default=0)),
                ('value', models.CharField(default=None, max_length=512)),
                ('active', models.BooleanField(default=True)),
                ('last_date_saved', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
