# Generated by Django 3.2.13 on 2022-10-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('patient_uid', models.CharField(max_length=20)),
                ('item_uid', models.CharField(default=None, max_length=45, null=True)),
                ('type', models.CharField(max_length=20)),
                ('subtype', models.CharField(default=None, max_length=20, null=True)),
                ('origin', models.CharField(default=None, max_length=20, null=True)),
                ('tnm_type', models.CharField(default=None, max_length=15, null=True)),
                ('diagnosis', models.CharField(max_length=45)),
                ('quantity', models.CharField(default=None, max_length=20, null=True)),
                ('quality', models.CharField(default=None, max_length=20, null=True)),
                ('note', models.TextField(blank=True, default=None, null=True)),
                ('_STATUS', models.IntegerField(default=-1)),
            ],
        ),
    ]
