# Generated by Django 3.2.13 on 2022-10-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_id',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='exposed_region',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='age_at_exposure',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='age_at_first_operation',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='country_at_accident',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='donor',
            name='country_current',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='donor',
            name='oblast_at_accident',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='donor',
            name='oblast_current',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='donor',
            name='patient_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='patient_uid',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age_category',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='donor',
            name='diagnosis',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dosimetry',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
