# Generated by Django 3.2.13 on 2022-10-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_auto_20221011_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age_at_exposure',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age_at_first_operation',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age_category',
            field=models.CharField(default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country_at_accident',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='country_current',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='diagnosis',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dosimetry',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='oblast_at_accident',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='oblast_current',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
