# Generated by Django 3.2.13 on 2022-10-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_auto_20221011_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=-1)),
                ('patient_uid', models.CharField(max_length=45, null=True)),
                ('edition', models.CharField(default=None, max_length=10, null=True)),
                ('classification_tumour', models.CharField(default=None, max_length=10, null=True)),
                ('classification_normal', models.CharField(default=None, max_length=10, null=True)),
                ('classification_metastatic', models.CharField(default=None, max_length=10, null=True)),
                ('stage', models.CharField(default=None, max_length=45, null=True)),
                ('operation_type', models.CharField(default=None, max_length=45, null=True)),
                ('relapse', models.BooleanField(default=False)),
                ('rit', models.BooleanField(default=False)),
                ('rit_value', models.IntegerField(default=None, null=True)),
                ('tsh_suppression', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
