# Generated by Django 3.2.13 on 2022-10-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_rename_clinical_clinicaltreatment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicalTreatment',
            new_name='Clinical_Treatment',
        ),
    ]
