# Generated by Django 3.2.13 on 2022-10-13 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_rename_clinicaltreatment_clinical_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_treatment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='clinical_treatment',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
