# Generated by Django 3.2.13 on 2022-10-13 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_auto_20221013_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_treatment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 16, 46, 28, 100396, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='clinical_treatment',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 16, 46, 28, 100418, tzinfo=utc), null=True),
        ),
    ]
