# Generated by Django 3.2.13 on 2022-10-13 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0012_auto_20221013_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinical_treatment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='clinical_treatment',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
