# Generated by Django 3.2.13 on 2022-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_auto_20221013_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uid', models.CharField(max_length=10, null=True)),
                ('gene', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
