# Generated by Django 3.2.13 on 2022-10-14 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0014_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctb_uid', models.CharField(max_length=45, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_uid', models.CharField(max_length=45, null=True)),
                ('project_label', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mdta_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdta_id', models.IntegerField(default=None, null=True)),
                ('item_uid', models.CharField(max_length=45, null=True)),
                ('item_label', models.CharField(max_length=45, null=True)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
