# Generated by Django 3.2.13 on 2022-10-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0015_mdta_mdta_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mdta_Items',
            new_name='Mdta_Item',
        ),
    ]
