# Generated by Django 3.2.13 on 2022-11-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0016_rename_mdta_items_mdta_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=256)),
                ('search_type', models.CharField(max_length=10)),
                ('case_count', models.IntegerField(default=0)),
                ('value', models.CharField(default=None, max_length=512)),
            ],
        ),
    ]
