# Generated by Django 3.2.13 on 2022-11-21 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0017_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='last_date_saved',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
