# Generated by Django 3.2.13 on 2022-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0018_auto_20221121_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
