# Generated by Django 3.2.13 on 2022-12-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0019_alter_filter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mdta',
        ),
        migrations.DeleteModel(
            name='Mdta_Item',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country_current',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='oblast_current',
        ),
    ]
