# Generated by Django 3.2.13 on 2022-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0020_auto_20221205_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age_at_exposure',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age_at_first_operation',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age_category',
            field=models.IntegerField(default=None, max_length=1, null=True),
        ),
    ]
