# Generated by Django 3.2.13 on 2022-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0021_auto_20221205_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age_category',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
