version: 2.1
commands:
  deployment_setup:
    steps:
      - run:
          name: "Set the Tier"
          command: |
            TIER=DEV
            if [[ ${CIRCLE_BRANCH} =~ isb-cgc-ctb-(prod|uat|test).* ]]; then
              TIER=$(awk -F- '{print toupper($4)}' \<<< ${CIRCLE_BRANCH})
            fi
            echo "export TIER=${TIER}" >> $BASH_ENV
            echo "Tier was identified as ${TIER} for branch ${CIRCLE_BRANCH}"
      - run:
          name: "Assign Project-level vars"
          command: |
            if [ ! -f deployment.key.json ]; then
              echo "Deployment JSON keyfile not found - loading from CircleCI."
              KEY=${DEPLOYMENT_KEY_CTB_DEV}
            else
              echo "Deployment JSON keyfile found."
              KEY="NA"
            fi
            CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_CTB_DEV}
            PROJECT_ID=${DEPLOYMENT_PROJECT_ID_CTB_DEV}
            BUCKET=${DEPLOYMENT_BUCKET_CTB_DEV}
            if [[ ${TIER} == "PROD" ]]; then
              KEY=${DEPLOYMENT_KEY_CTB_PROD}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_CTB_PROD}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_CTB_PROD}
              BUCKET=${DEPLOYMENT_BUCKET_CTB_PROD}
              echo "Using production project and related deployment SA and bucket."
            elif [[ ${TIER} == "UAT" ]]; then
              KEY=${DEPLOYMENT_KEY_CTB_UAT}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_CTB_UAT}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_CTB_UAT}
              BUCKET=${DEPLOYMENT_BUCKET_CTB_UAT}
              echo "Using UAT project and related deployment SA and bucket."
            elif [[ ${TIER} == "TEST" ]]; then
              KEY=${DEPLOYMENT_KEY_CTB_TEST}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_CTB_TEST}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_CTB_TEST}
              BUCKET=${DEPLOYMENT_BUCKET_CTB_TEST}
              echo "Using test project and related deployment SA and bucket."
            elif [[ ${TIER} == "DEV" ]]; then
              echo "Using development/default project and related deployment SA and bucket."
            else
              echo "[ERROR] - Unrecognized tier: ${TIER} - exitng."
              exit 1
            fi

            echo "export DEPLOYMENT_TIER=${TIER}" >> $BASH_ENV
            echo "export DEPLOYMENT_KEY=\"${KEY}\"" >> $BASH_ENV
            echo "export DEPLOYMENT_CLIENT_EMAIL=${CLIENT_EMAIL}" >> $BASH_ENV
            echo "export DEPLOYMENT_PROJECT_ID=${PROJECT_ID}" >> $BASH_ENV
            echo "export DEPLOYMENT_BUCKET=${BUCKET}" >> $BASH_ENV

            echo "Project settings assigned:"
            echo "Deployment client: ${CLIENT_EMAIL}"
            echo "Deployment project: ${PROJECT_ID}"
            echo "Deployment bucket: gs://${BUCKET}"

  deployment_config:
    steps:
      - run:
          name: "Set tier-specific configuration file"
          command: |
            sudo -E /bin/bash ./shell/pull_config.sh
            xargs -a deployment_config.txt -I{} echo "export {}" >> $BASH_ENV
            # Set up test/deployment database values
            echo "export MYSQL_ROOT_PASSWORD_BUILD=ctb" >> $BASH_ENV
            echo "export DATABASE_NAME_BUILD=build_database" >> $BASH_ENV
            echo "export DATABASE_PASSWORD_BUILD=ctb" >> $BASH_ENV
            echo "export DATABASE_USER_BUILD=django-user" >> $BASH_ENV
            echo "export DATABASE_HOST_BUILD=127.0.0.1" >> $BASH_ENV

  auth:
    steps:
      - run:
          name: "Service Account Auth and Project Settings"
          command: |
            sudo -E /bin/bash ./shell/gcloud_authenticate.sh

  install_cloud_sdk:
    steps:
      - run:
          name: "Install CloudSDK"
          command: |
            echo "export CLOUDSDK_CORE_DISABLE_PROMPTS=1" >> $BASH_ENV
            sudo apt-get update -qq
            sudo apt-get install ca-certificates python3-distutils apt-transport-https gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update -qq
            sudo apt-get -y install google-cloud-sdk

  run_tests:
    steps:
      - run:
          name: "Run Tests"
          command: |
            sudo -E /bin/bash ./shell/run_tests.sh

jobs:
  build_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/isb-cgc-ctb
    docker:
      - image: cimg/python:3.9.2
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: "ctb"
          MYSQL_ROOT_PASSWORD: "ctb"
          MYSQL_DATABASE: "build_database"
    steps:
      - checkout
      - run:
          name: Fix for bug with Git and Ubuntu 20+
          command: |
            SHA=$(git rev-list -1 HEAD)
            echo "export APP_SHA=${SHA:0:7}" >> $BASH_ENV
      - run:
          name: Set Python Path
          command: |
            echo "export PYTHONPATH=/home/circleci/${CIRCLE_PROJECT_REPONAME}:/home/circleci/${CIRCLE_PROJECT_REPONAME}/lib" >> $BASH_ENV
      - restore_cache:
          keys:
            - ctb-webapp-lib-{{ checksum "requirements.txt" }}
      - deployment_setup
      - run:
          name: Install Dependencies
          command: |
            sudo -E /bin/bash ./shell/install-deps.sh
      - save_cache:
          key: ctb-webapp-lib-{{ checksum "requirements.txt" }}
          paths:
            - ./lib
      - auth
      - deployment_config
      - run:
          name: Staging and Database testing
          command: |
            sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
            sudo -E /bin/bash ./shell/database-setup.sh
      - run:
          name: Compare Config
          command: |
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/deployment_config.txt"
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/${ENV_FILE}"
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/${WEBAPP_APP_YAML}"
      - save_cache:
          key: ctb-webapp-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - ./accounts
            - ./adminrestrict
            - ./.git
            - ./shell
            - ./google_helpers
            - ./static
            - ./ctb
            - ./offline
            - ./donors
            - ./searches
            - ./request_logging
            - ./scripts
            - ./templates
            - ./Dockerfile
            - ./main.py
            - ./.dockerignore
            - ./app.yaml
            - ./gunicorn.conf.py
            - ./manage.py
            - ./txt
            - ./json
            - ./.env
            - ./version.env

  deploy_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/isb-cgc-ctb
    docker:
      - image: cimg/python:3.9.2
    steps:
      - restore_cache:
          keys:
            - ctb-webapp-{{ .Branch }}-{{ .Revision }}-
      - install_cloud_sdk
      - deployment_setup
      - auth
      - deployment_config
      - deploy:
          command: |
            sudo -E rm -rf ./lib
            sudo -E /bin/bash ./shell/unpack_for_deployment.sh
            sudo -E gcloud config set app/cloud_build_timeout 1800
            sudo -E gcloud app deploy --verbosity=debug ./app.yaml --quiet
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only:
                - main
                - isb-cgc-ctb-test
                - isb-cgc-ctb-uat
                - isb-cgc-ctb-prod
