# Generated by Django 3.2.13 on 2022-05-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('N', 'Continuous Numeric'), ('C', 'Categorical String'), ('M', 'Categorical Number'), ('T', 'Text'), ('S', 'String'), ('D', 'Date')], default='C', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('preformatted_values', models.BooleanField(default=False)),
                ('units', models.CharField(blank=True, max_length=256, null=True)),
                ('default_ui_display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search_Perms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.CharField(choices=[('READER', 'Reader'), ('OWNER', 'Owner')], default='READER', max_length=10)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.search')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('numeric_op', models.CharField(blank=True, choices=[('B', '_btw'), ('GE', '_gte'), ('LE', '_lte'), ('G', '_gt'), ('L', '_lt')], max_length=4, null=True)),
                ('value_delimiter', models.CharField(default=',', max_length=4)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.attribute')),
                ('resulting_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.search')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_Display_Values',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=256)),
                ('display_value', models.CharField(max_length=256)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searches.attribute')),
            ],
            options={
                'unique_together': {('raw_value', 'attribute')},
            },
        ),
    ]
