name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - "*_dev"
      - "*_qa"

env:
  TZ: America/New_York

jobs:
  Deploy:
    permissions:
      contents: "read"
      id-token: "write"
    # needs: build
    runs-on: ubuntu-latest
    environment: ${{ (endsWith(github.ref, '_dev') && 'dev') || (endsWith(github.ref, '_qa') && 'qa') || '' }}

    steps:
    - uses: "actions/checkout@v4"
  
    # Set up Google Cloud SDK
    - name: "Set up Google Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v2"

    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v2"  
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - id: "generate_app_yaml"
      name: "Generate app.yaml"
      run: envsubst < app.template.yaml > app.yaml

    - name: Generate .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - id: "deploy"
      uses: 'google-github-actions/deploy-appengine@v2'
      env:
        CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800 # 30 minutes
      with:
        project_id:  ${{ secrets.PROJECT_ID }}
        working_directory: ${{ github.workspace }}
        deliverables: app.yaml
        flags: "--verbosity=debug --service-account=${{ secrets.APP_SERVICE_ACCOUNT }}"
