name: Build and Deploy
on:
  push:
    branches:
      - main
      - isb-cgc-ctb-test
      - isb-cgc-ctb-uat
      - isb-cgc-ctb-prod
      - actions


env:
  TZ: America/Los_Angeles

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: ctb
          MYSQL_ROOT_PASSWORD: "***"
          MYSQL_DATABASE: build_database

    steps:
    - uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set up environment variables
    - name: Set environment variables
      run: |
        # Your environment variable setup logic here

    # Run tests
    - name: Run tests
      run: |
        # Your test script here

    # Upload artifacts
    - name: Upload artifacts
      uses: actions/cache@v4
      with:
        key: ctb-webapp
        path: |
          accounts
          adminrestrict
          .git
          shell
          google_helpers
          static
          ctb
          offline
          donors
          searches
          request_logging
          scripts
          templates
          Dockerfile
          main.py
          .dockerignore
          app.yaml
          gunicorn.conf.py
          manage.py
          txt
          json
          .env
          version.env


  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: webapp

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # Authenticate with Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    # Deploy to App Engine
    - name: Deploy to App Engine
      id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v2'
      with:
        build_env_vars: |-
          FOO=bar
          ZIP=zap
        env_vars: |-
          FOO=bar
          ZIP=zap