name: testcxn GCP and List Instances

on:
  workflow_dispatch:

env:
  PROJECT_ID: nih-nci-cbiit-ctb-dev

jobs:
  setup-prepare-list:
    name: Setup, Prepare,
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider:  projects/1073752893176/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: ctb-deployer2@nih-nci-cbiit-ctb-dev.iam.gserviceaccount.com

    # List the instances in the project
    - name: List Instances
      run: |-
        gcloud compute instances list --project $PROJECT_ID
